# Site settings
title: Open Source Design - Job Board
email:
description: > # this means to ignore newlines until "baseurl:"
  We are a community of designers and developers aiming to push more open design processes and improve the design of open source apps
baseurl: "/jobs" # the subpath of your site, e.g. /blog/
url: "http://opensourcedesign.net" # the base hostname & protocol for your site
twitter_username: opensrcdesign
github_username:  opensourcedesign

# Build settings
markdown: kramdown
permalink: /:month-:day-:year/:title.html

kramdown:
  input: GFM

status: &status
  - name: "Open"
    value: "open"
  - name: "Started"
    value: "started"
  - name: "Completed"
    value: "completed"
  - name: "Rejected"
    value: "rejected"

roles: &roles
  - name: "General Design Help"
    value: "general-help"
  - name: "Font Design"
    value: "font-design"
  - name: "Logo Design"
    value: "logo-design"
  - name: "Icon Design"
    value: "icon-design"
  - name: "Styleguide"
    value: "styleguide"
  - name: "Website Design"
    value: "website-design"
  - name: "App Interface Design"
    value: "app-interface-design"
  - name: "User Experience Design"
    value: "user-experience-design"
  - name: "Usability Testing"
    value: "usability-testing"
  - name: "Wireframe Prototyping"
    value: "wireframe-prototyping"
  - name: "Data Visualization"
    value: "data-visualization"
  - name: "Information Architecture"
    value: "information-architecture"
  - name: "Product Design"
    value: "product-design"
  - name: "Print Design"
    value: "print-design"
  - name: "Packaging Design"
    value: "packaging-design"
  - name: "Other"
    value: "other"

compensation: &compensation
  - name: "Gratis"
    value: "gratis"
  - name: "Negotiable"
    value: "negotiable"
  - name: "Trade"
    value: "trade"
  - name: "$500 or less"
    value: "500"
  - name: "$1000 or less"
    value: "1000"
  - name: "$5000 or less"
    value: "5000"
  - name: "$5000 or more"
    value: "5000-more"
  - name: "Part Time Position"
    value: "part-time"
  - name: "Full Time Position"
    value": "full-time"

# Prose Config - what is seen at https://edit.opensourcedesign.net
# Docs: https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: 'jobs'
  metadata:
    jobs:
      - name: "_id"
        field:
          element: "hidden"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "jobs"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "organization"
        field:
          element: "text"
          label: "Organization"
          value: ""
      - name: "org_url"
        field:
          element: "text"
          label: "Organization URL"
          value: ""
      - name: "status"
        field:
          element: "select"
          label: "Job Status"
          placeholder: "Job Status"
          options: *status
          selected: ""
      - name: "role"
        field:
          element: "multiselect"
          label: "Roles"
          placeholder: "Roles"
          options: *roles
          selected: ""
      - name: "compensation"
        field:
          element: "select"
          label: "Compensation"
          placeholder: "Compensation"
          options: *compensation
          selected: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Tags"
          value: ""
